-- ====================================================================
-- Pass-Cast Premium 및 실시간 광고 노출 집계 고도화 데이터베이스 스키마
-- Supabase SQL Editor에 복사하여 실행해 주세요.
-- ====================================================================

-- 1. subscriptions (프리미엄 기간제 만료일 관리 테이블)
CREATE TABLE IF NOT EXISTS public.subscriptions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    expires_at TIMESTAMPTZ,
    status VARCHAR(50) DEFAULT 'active',
    created_at TIMESTAMPTZ DEFAULT now()
);

-- RLS (Row Level Security) 설정 및 정책 정의
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow individual read access" ON public.subscriptions;
CREATE POLICY "Allow individual read access" ON public.subscriptions
    FOR SELECT TO authenticated USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow service role write access" ON public.subscriptions;
CREATE POLICY "Allow service role write access" ON public.subscriptions
    FOR ALL TO service_role USING (true);

DROP POLICY IF EXISTS "Allow anon read all" ON public.subscriptions;
CREATE POLICY "Allow anon read all" ON public.subscriptions
    FOR SELECT TO anon, authenticated USING (true);

-- 2. ad_impressions (실시간 광고 노출 로그 테이블)
CREATE TABLE IF NOT EXISTS public.ad_impressions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    placement VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT now()
);

-- RLS (Row Level Security) 설정 및 정책 정의
ALTER TABLE public.ad_impressions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public insert" ON public.ad_impressions;
CREATE POLICY "Allow public insert" ON public.ad_impressions
    FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow read for all" ON public.ad_impressions;
CREATE POLICY "Allow read for all" ON public.ad_impressions
    FOR SELECT TO anon, authenticated USING (true);

-- 3. app_settings (공격적 마케팅 토글 컬럼 추가 마이그레이션)
ALTER TABLE public.app_settings ADD COLUMN IF NOT EXISTS force_gating BOOLEAN DEFAULT false;

